config/routes.rb
Webknowadmin::Application.routes.draw do


  root to: 'admin_users#home'

  
  match '/signin', to: 'sessions#new', via: 'get'
  #match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]



  resources :admin_users do
    collection do
      post :dbclear
    end
  end

  resources :admin_users do
    collection do
      post :dbdelete
    end
  end

  match '/admin_users_index', to: 'admin_users#index', via: 'get'  
  match '/admin_users_new', to: 'admin_users#new', via: 'get'  

  resources :admin_users



  get "static_pages/ajaxpostex"
  get "static_pages/serverside"
  get "static_pages/postjsonex"
  
  match '/JournalPosterPositions-1', to: 'journal1poster_positions#index', via: 'get'
  match '/JournalPosterCreate-1', to: 'journal1poster_positions#create', via: 'post'

  # match '/JournalPosterPositionsCoord', :to => 'journal1poster_positions#coord', :as => 'JournalPosterPositionsCoord', :via => [:post]
  # match '/publisher_journalposter_purchases/receipt', :to => 'publisher_journalposter_purchases#receipt', :as => 'publisher_journalposter_purchases_receipt', :via => [:get]
  
  # resources :journal1poster_positions do
    # collection do
      # post :demo_test_post
    # end
  # end

  # resources :journal1poster_positions do
    # collection do
      # post :coord
    # end
  # end
  
  resources :journal1poster_positions do
    collection do
      post :dbdelete
    end
  end
  
  # resources :journal1poster_positions do
    # member do
      # get 'coord'
    # end
  # end

  resources :journal1poster_positions





  match '/JournalPosterPositions-2', to: 'journal2poster_positions#index', via: 'get'
  resources :journal2poster_positions

  match '/JournalPosterPositions-3', to: 'journal3poster_positions#index', via: 'get'
  resources :journal3poster_positions

  match '/JournalPosterPositions-4', to: 'journal4poster_positions#index', via: 'get'
  resources :journal4poster_positions

  match '/JournalPosterPositions-5', to: 'journal5poster_positions#index', via: 'get'
  resources :journal5poster_positions




  match '/poster_map_1', to: 'journalposter__maps#index', via: 'get'
  resources :journalposter_maps








end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id              :integer          not null, primary key
#  name_first      :string(255)
#  name_last       :string(255)
#  username        :string(255)
#  email           :string(255)
#  password        :string(255)
#  password_digest :string(255)
#  remember_token  :string(255)
#  hashed_password :string(255)
#  salt            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class AdminUser < ActiveRecord::Base
  
  attr_accessible :id, 
                  :name_first, 
                  :name_last, 
                  :email, 
                  :username, 
                  :password, 
                  :password_confirmation, 
                  :created_at, 
                  :updated_at


  has_many :admin_user_images
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 4 }
    
  
      
    
    def AdminUser.new_remember_token
      SecureRandom.urlsafe_base64
    end
  
    def AdminUser.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
    
    def self.dbdelete
        self.connection.execute("DELETE FROM admin_users")
    end
    
    def self.dbclear
        self.connection.execute("ALTER SEQUENCE admin_users_id_seq RESTART WITH 1")
    end
    
    
        
    # def feed
      # Micropost.from_users_followed_by(self)
    # end
#   
    # def following?(other_user)
      # relationships.find_by(followed_id: other_user.id)
    # end
#   
    # def follow!(other_user)
      # relationships.create!(followed_id: other_user.id)
    # end
#   
    # def unfollow!(other_user)
      # relationships.find_by(followed_id: other_user.id).destroy!
    # end
  
    private
  
      def create_remember_token
        self.remember_token = AdminUser.encrypt(AdminUser.new_remember_token)
      end


  
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  
  layout 'admin_users'
  
  helper_method :sort_column, :sort_direction

  # before_action :signed_in_user
  
  #before_action :signed_in_user,
                #only: [:index, :edit, :update, :destroy, :following, :followers]
  
  #before_filter :confirm_logged_in  
  
  def index

    @admin_users = AdminUser.order(sort_column + " " + sort_direction).paginate(page: params[:page]).per_page(5)
    
  end
  
  def home
    
  end
  
  
  # def list
    # @admin_users = AdminUser.paginate(page: params[:page]).per_page(5)
  # end
  
  def new
    #@account_type = params[:id]
    @admin_user = AdminUser.new    
  end
  
  def view
    # @user = User.find(params[:id])
        
    # respond_to do |format|
      # format.html
      # format.js      
    # end
    
  end
    
  def show
    @admin_user = AdminUser.find(params[:id])    
  end
    
  
  def create
    
    # file_dir = 'public/repository/image_eric.jpg'    
    # AdminUser.photo_from_url(Rails.root.join(file_dir))     
    
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
        
        redirect_to action: "index"
        
        # sign_in @admin_user
      
        # case account_type= params[:account_type]
        # when "School"
          # redirect_to(:controller => 'institutes', :action => 'new')
        # when "Teacher"
          # redirect_to(:controller => 'teachers', :action => 'new')
        # when "Student"
          # redirect_to(:controller => 'students', :action => 'new')
        # when "Publisher"
          # redirect_to(:controller => 'publishers', :action => 'new')
        # else
          # # alert error redirect
        # end
        
    else
      render 'new'
    end
    
  end
  
  def edit
    #render text: "in edit"
  end
  
  def update
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    admin_user = AdminUser.find(params[:id])
    admin_user.delete
    #flash[:notice] = "User destroyed."
  end
  
  def dbdelete
      AdminUser.dbdelete
      redirect_to action: "index"
      # render text: 'dbdelete'
  end
  
  def dbclear
      AdminUser.dbclear
      redirect_to action: "index"
      # render text: 'dbclear'
  end
  
  
  # def confirm_logged_in
    # unless session[:user_id]
      # redirect_to(login_path)
      # return false 
    # else
      # return true
    # end
  # end
# 
  # def logout
    # session[:user_id] = nil
    # session[:username] = nil
    # #flash[:notice] = "You have been logged out."
    # #redirect_to("login_path")
# 
    # redirect_to(:controller => 'admin_users', :action => 'home')
#     
#     
    # #render text: "in logout"
  # end
  
  
  private

    def admin_user_params
      params.require(:admin_user).permit(      
                                          :name_first, 
                                          :name_last, 
                                          :email, 
                                          :username, 
                                          :password, 
                                          :password_confirmation, 
                                          :created_at, 
                                          :updated_at,
                                        )
                                        
    end
    
    def sort_column
      AdminUser.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
    
  # def get_message
#     
    # respond_to do |format|
      # format.html
      # format.js      
    # end    
  # end
  
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end

end

app/views/admin_users/_form_admin.html.erb
<%= error_messages_for(@admin_user) %>

<table summary="Admin user form fields">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
</table>

<%= link_to "Return", session[:back_page] %>

app/views/admin_users/_index.html.erb
	<div class="main">
	
		<div id="scroll1" class="scrollbox-both" onscroll="scrollPos();">	
			
			<% if @admin_users.any? %>
				
				<%= hidden_field_tag :direction, params[:direction] %>
				<%= hidden_field_tag :sort, params[:sort] %>	
				<%= hidden_field_tag :pos, params[:pos] %>	
				
				<h5>Record Count: <%= @admin_users.count %></h5>
    	    				
				<table id="admin-users" title="AdminUsers" >    	  
					  	
			       <colgroup>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
				       <col class="member-table"></col>
			       </colgroup>

				  <tr align="left">
				  	
				    <th class="member-table" id="th_view" field="view" style="width: 50px"><div class="header-shift"><h4></h4></div></th>
				    <th class="member-table" id="th_delete" field="delete" style="width: 50px;"><div class="header-shift"><h4></h4></div></th>
				  	
				    <th class="member-table" id="th_id" field="id" style="width: 50px"><div id="id" class="header-shift"><h4><%= sortable "id", "ID" %></div></th>
				    <th class="member-table" id="th_created_at" field="created_at" style="width: 100px"><div id="id" class="header-shift"><h4><%= sortable "created_at", "Created" %></div></th>
				    <th class="member-table" id="th_updated_at" field="updated_at" style="width: 100px"><div id="id" class="header-shift"><h4><%= sortable "updated_at", "Updated" %></div></th>
				    <th class="member-table" id="th_username" field="username" style="width: 100px"><div id="username" class="header-shift"><h4><%= sortable "username", "Username" %></h4></div></th>
				    <th class="member-table" id="th_email" field="email" style="width: 300px"><div id="" class="header-shift"><h4><%= sortable "email", "Email" %></h4></div></th>
				  </tr>
				<% @admin_users.each do |admin_user| %>
				  <tr align="left" class="tr-events">
				  	
				    <td><h5><%= link_to('View', {:action => 'show', :id => admin_user.id, :class => 'member-table'}) %></h5></td>
	
				    <td>
				    	<div style="position: relative; bottom: -2px">
					    	<h5>
							   	<% delete_msg = "Delete ID: " + admin_user.id.to_s + " ?" %>
								<%= button_to "Delete", {:action => 'destroy', :id => admin_user.id}, :method => :delete, :confirm => delete_msg, :class => 'delete-btn' %>
							</h5>
						</div>
					</td>
				  	
				    <td><h5 class="member-table"><%= admin_user.id %></h5></td>
				    <td><h5 class="member-table"><%= admin_user.created_at.to_formatted_s(:db) %></h5></td>
				    <td><h5 class="member-table"><%= admin_user.updated_at.strftime("%B %e, %Y") %></h5></td>    
				    <td><h5 class="member-table"><%= admin_user.username %></h5></td>
				    <td><h5 class="member-table"><%= admin_user.email %></h5></td>
				    			      
				  </tr>
				<% end %>

				<!-- number_to_currency(product.price) -->
				
				</table>			
							
				  <%= will_paginate @admin_users %>							
							
			<% else %>
						
				<h3>No record for Admin Users</h3>
				
			<% end %>
			
		</div>
		
	</div>

   
	<script>
		
        function scrollPos() {
            $("#pos").html($("#scroll1").scrollLeft());
        }
		
		function moveScroll() {
			$("#scroll1").scrollLeft($("#pos").html());
		}

				
				
		$(function() {
		
			 // $('#loading').fadeOut(1000);
				
		
			// img = $('<img />');
//  			
			// img.bind('loading_import', function() {
// 				
				// $('#join_image').css({
					// visibility: 'visible'
				// })
// 				
			    // $('#loading').fadeOut(1000);
// 
				// // // setTimeout( function(){
					// // // centerSignin();
					// // // showSignin();
					// // // formValidate();
				// // // }, 1000);
			// });
		
		
		
			// $("#get-import").on('click', function() {
			    // $.post({
			    	// //type: "POST",
			      	// url: "/stores/import"
			    // });			
			// });
		
		
		
		
		
		
    		var $cols = $('colgroup');

			$("table#admin-users tr:nth-child(even)").addClass('gray');
			$("table#admin-users tr:nth-child(odd)").addClass('white');

			// #  id           :integer			3  
			// #  name_type    :string(50)		4
			// #  salutation   :string(50)		5
			// #  name_first   :string(50)		6
			// #  name_last    :string(50)		7
			// #  name_title   :string(50)		8
			// #  institute    :string(100)		9
			// #  department   :string(100)		10
			// #  address_1    :string(100)		11
			// #  address_2    :string(100)		12
			// #  city         :string(50)		13
			// #  state        :string(100)		14
			// #  zip          :string(50)		15
			// #  country      :string(100)		16
			// #  phone        :string(50)		17
			// #  fax          :string(50)		18
			// #  phone_direct :string(50)		19
			// #  phone_mobile :string(50)		20
			// #  email        :string(100)		21
			// #  website      :string(100)		22


			var cell;
			var cellIndex;
			var row;
			var rowIndex;
			var header;
			var cellTh;
			var cellIndexTh;
			
			$("table#admin-users th").mouseover ( function () {

				cellTh = $(this).closest('th');
				cellIndexTh = cellTh[0].cellIndex;
				cellIndexTh += 1;
				
				$("table#admin-users td:nth-child(" + cellIndexTh + ")").addClass('hover-col');
				$(this).addClass('hover-col');
				
			}).mouseout ( function() {
				
				$("table#admin-users td:nth-child(" + cellIndexTh + ")").removeClass('hover-col');				
				$(this).removeClass('hover-col');
				
			});
			
			$("table#admin-users td").mouseover ( function () {
				
				cell = $(this).closest('td');
				cellIndex = cell[0].cellIndex;
				cellIndex += 1;
				row = cell.closest('tr');
				rowIndex = row[0].rowIndex;
				
				switch(cellIndex)
				{
				case 1:
					header = "th_view"	  
				  break;
				case 2:
					header = "th_delete"	  
				  break;
				case 3:
					header = "#th_id"	  
				  break;
				case 4:
					header = "#th_username"	  
				  break;				  
				case 5:
					header = "#th_email"	  
				  break;

				default:
					//
				}				

				$(header).addClass('hover-col');
		
				if (rowIndex % 2 === 0) {
					$("table#admin-users td:nth-child(" + cellIndex + ")").addClass('hover-col');
					row.removeClass('gray').addClass('hover-row');					
				}
				else {
					$("table#admin-users td:nth-child(" + cellIndex + ")").addClass('hover-col');
					row.removeClass('white').addClass('hover-row');										
				}		
			}).mouseout( function(){

				$(header).removeClass('hover-col');
				
				if (rowIndex % 2 === 0) {
					$("table#admin-users td:nth-child(" + cellIndex + ")").removeClass('hover-col');
					row.removeClass('hover-row').addClass('gray');					
				}
				else {
					$("table#admin-users td:nth-child(" + cellIndex + ")").removeClass('hover-col');
					row.removeClass('hover-row').addClass('gray');					
				}		
			});
			
			var rowSelect = -1;			
			
			$("table#admin-users td").on('click', function () {
	
				cell = $(this).closest('td');
				btn_delete = $(this).closest('form');
				row = cell.closest('tr');
				rowIndex = row[0].rowIndex;

				if (rowSelect !== -1) {
					$("table#admin-users tr").removeClass('row-select');
				}
				
				rowSelect = rowIndex;
				row.addClass('row-select');
				btn_delete.removeClass('btn-color').addClass('btn-color-select');
			});
	
	
			
			$(document).on('click', function(event) {
				// alert(event.target);
				elem = event.target.className;
				if ((elem === 'hover-col') || (elem === 'delete-btn') || (elem === 'member-table')) {
					//
				}
				else {
					$("table#admin-users tr").removeClass('row-select');					
				}
			});
		});

		// $(document).on('click', function() {
			// if ((rowSelect !== -1)) {
				// //$("table#admin-events tr").removeClass('row-select');
			// }
			// rowSelect = -1;
			// tableClicked = false;
		// })

		//$(document).ready(function () {
			// $('*[data-confirm]').click(function(){
				// // alert('delete clicked');				
		    	// return confirm($(this).attr('data-confirm'));
		  	// });
		//});
			
	</script>

app/views/admin_users/_menu.html.erb
<% provide(:title, 'Admin Menu') %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as: <%= session[:username] %></div>
  <ul>
  	<li><%= link_to 'Contact List', list_path %></li>
    <li><%#= link_to("View Messages", :controller => 'contacts') %></li>
    <li><%#= link_to("Manage Admin Users", :controller => 'admin_users') %></li>
    <li><%= link_to("Logout", :controller => 'admin_users', :action => 'logout' ) %></li>
    
    <li><%#= link_to("Logout", :controller => 'logout' ) %></li>
  </ul> 
</div>

app/views/admin_users/delete.html.erb
<h1>AdminUsers#admin_delete</h1>
<p>Find me in app/views/admin_users/admin_delete.html.erb</p>

app/views/admin_users/edit.html.erb
<h1>AdminUsers#admin_edit</h1>
<p>Find me in app/views/admin_users/admin_edit.html.erb</p>

app/views/admin_users/home.html.erb
<% provide(:title, 'Admin Home') %>

	<style>
	
		#signin-page {
			height: 800px;
		}
	
		#signin-page #signin-page-inner {
		    width: 80%;
		    margin: 0 auto;
		}	

		div .table-signin {
			display: table;
			background-color: #DEDB3C;
			width: 880px;
			border-radius: 20px;
			border:2px solid #254520;
			box-shadow: 1px 1px 10px #888888;
			padding-top: 40px;
			padding-bottom: 40px;
			padding-left: 60px;
		}
	
		.table-signin p {
			font-family: msyh; 
			font-size: 16px;
			color: #005187;"
		}
		
	</style>


	<div id="signin-page">
		
		<header>
	
			<%= render 'share/backtotop' %>
			
			<div style="height: 70px;"></div>
			
		</header>
		
		
		<div id="signin-page-inner">
			
			<div class="table-signin">
				<div class="row">
					
					<div class="cell-100percent" tabindex="1">
						
						<p>Admin Home</p>
												
					</div>
					
				</div>
				
			</div>
			
		</div>	
		
	</div>					
					
	<script>

		$(window).load( function() {
		//$(document).ready(function(){

		});
	
	</script>

app/views/admin_users/index.html.erb
<% provide(:title, 'Admin Users') %>

					
	<style>
	
		#signin-page {
			height: 1300px;
		}
	
		#signin-page #signin-page-inner {
		    width: 100%;
		    margin: 0 auto;
		}	

		div .table-signin {
			display: table;
			background-color: #E3DDCF;
			width: 1000px;
			border-radius: 0px;
			
			/*border:2px solid #254520;*/
						
			/*box-shadow: 1px 1px 3px #888888;*/			
			
			padding-top: 40px;
			padding-bottom: 40px;
			padding-left: 10px;
			padding-right: 10px;			
		}

		.table-signin p {
			font-family: msyh; 
			font-size: 16px;
			color: #005187;"
		}
		
		
		
		#import.signin-btn {
		  	width: 70px;
		  	height: 20px;			
		}    	   
    	    	
		.signin-btn {
		  	display: inline-block;
		  	text-decoration: none; 
		  	background: linear-gradient(#000, #000);
		  	text-shadow: 1px 1px 1px #0E86B2; 
		  	border-radius: 4px;
		}
	
		.signin-btn:focus {
		  background: #CCC; 
		  color: #5F7A2A;
		  box-shadow: inset 0 1px 0 rgba(200,200,200,0.2);
		}
		
		.signin-btn:hover { 
		  box-shadow: inset 0 1px 1px rgba(255,255,255,0.2), 
		  inset 0 1.5em 1em rgba(255,255,255,0.3);
		}
		
		.signin-btn:active { 
		  box-shadow: inset 0 1px 1px rgba(255,255,255,0.2), 
		  inset 0 1.5em 1em rgba(0,0,0,0.3); 
		}
		
	</style>

    <style>
    	
    	.main {
    		font-family:Arial, Helvetica, sans-serif;
    		font-size: 20px;
    		color: black;
    		height: 500px;
    	}
    	
    	.links {
    		font-family:Arial, Helvetica, sans-serif;
    		font-size: 13px;
    		color: brown;    		
    	}
    	
    	h1 {
    		font-size: 22px;
    	}
    	h2 {
    		font-size: 18px;
    	}
    	h4 {
    		font-size: 16px;
    		font-weight: 600;
    	}    	
    	h5 {
    		font-size: 12px;
    	}    	    	
    	p {
    		font-size: 12px;
    	}
    	
    	.bar {
    		font-size: 16px;
    		font-weight: 400;
    	}
    	
		.input-upload {
			font-family: Arial, Helvetica, sans-serif;
			font-size: 16px;
			width: 600px;
			height: 24px;
			border-style:solid;
			background-color: #fff;
			border-color: #000;
			border-width: 1px;
			padding-left: 6px;
			color: #888;
		}
    	
    	.submit-upload {
			font-family: Arial, Helvetica, sans-serif;
			font-size: 16px;
    		height: 24px;
    	}
    	
    	#admin-users {
    		width: 1200px; 
    	}
    	table#admin-users th {
    		padding-left: 0px;
    	}    	    	
    	table#admin-users tr {
    		height: 20px;
    	}    	
    	table#admin-users td {
    		vertical-align: bottom;    		
    		padding-top: 0px;
    		padding-bottom: 4px;       		    		    		
    	}
		/*table#admin-users tr:nth-child(even) {
			background: #CCC			
		}
		table#admin-users tr:nth-child(odd) {
			background: #FFF
		}    	*/
		
		    	
    	.gray {
			background: #CCC			    		
    	}
    	.white {
			background: #fff    		
    	}
    	.hover-col {
    		background-color: rgba(0, 0, 0, 0.1);
    	}
    	
		.hover-row {
			background-color: #FAC0C1;
		}
		/*.hover-col {
			background-color: #FCD7D7 !important;
		}*/
		.row-select {
			color: #fff;			
			background-color: brown;
		}
		.btn-color-select {
			color: #fff;	
		}
		.btn-color {
		  	color: #A31C1C;			
		}
		    	
		.delete-btn {
		  	display: inline-block;
		  	text-decoration: none; 
		  	width: 50px;
		  	height: 20px;
		  	background: inherit;
		  	border-width: 0px;
		}
		.delete-btn:focus {
		}
		.delete-btn:hover { 
		  	text-decoration: underline; 
		}
		.delete-btn:active { 
		  	text-decoration: underline; 
		}

		.header-shift {
			padding-left: 0px;
		}    	    	

		.reset-db-btn {
		  	width: 200px;
		  	height: 20px;
		}
    	    	
    	    	
    	    	
    	    	
    </style>

	<style>
		
		.scrollbox-both {
	 		height:520px;
	 		width:1200px;
	 		overflow:scroll;
	 		border:1px solid #651375;		
		}
				
	</style>




	<div id="signin-page">
		
		<header>
	
	    	<div id="pos" style="display: none;"></div>

			<%= render 'share/backtotop' %>

			<div style="height: 100px;"></div>
			
		</header>
		
		<div id="signin-page-inner">
			
			<table width="1000px" style="float: right;">
				<tr>
					<td>
						<%= link_to 'New', admin_users_new_path %>
					</td>
					<td style="width: 100px; text-align: right;">
				    	<div>
					    	<h5>
							   	<% delete_all_msg = "Delete all records?" %>
								<%= button_to "Delete All Records", {:action => 'dbdelete'}, :method => :post, :confirm => delete_all_msg, :class => 'reset-db-btn' %>
							</h5>
						</div>
					</td>
					<td style="width: 100px; text-align: right;">
				    	<div>
					    	<h5>
							   	<% reset_db_msg = "Reset database index?" %>
								<%= button_to "Database Reset Index", {:action => 'dbclear'}, :method => :post, :confirm => reset_db_msg, :class => 'reset-db-btn' %>
							</h5>
						</div>
					</td>
				</tr>		
			</table>	
			<div style="clear: both;">
			
			<div class="table-signin">
				
				<div class="row">
					
					<div class="cell-100percent" tabindex="1">


						  						
							<div id="admin_users">
								
								<%= render 'admin_users/index'%>

							</div>
												
					</div>
					
				</div>
				
			</div>
			
		</div>	
		
	</div>					

	<script>

		$(document).on('click','#admin_users th a, #admin_users .pagination a',function(){
		    $.getScript(this.href);
		    return false;
		});
	
	</script>
					

app/views/admin_users/index.js.erb
alert('ajax works in admin_users');

$("#admin_users").html("<%= escape_javascript(render("admin_users/index")) %>");
moveScroll();

app/views/admin_users/index_old.html.erb
<div class="wrapper row1">
  <div id="header" class="clear">
  	
	<%#= render 'share/title'%>
  	
    <%#= render 'share/site_search' %>  
    
    <%#= render 'share/navigate' %>  
    
  </div>
</div>

<div class="wrapper row3">
  <div id="container" class="clear">
    <div id="content">
      <div id="comments" style="height: 480px">

	 		<p><%= render(:partial => "share/menu_admin") %></p>            	
  	
			<p><%= link_to "&laquo; Back".html_safe, :back %></p>

      		<h2><p><em>Administration</em></p></h2>
    
      </div>
    </div>
  </div>
</div>

app/views/admin_users/list.html.erb
<% provide(:title, 'Users') %>

	<% if @admin_users.any? %>

    <table id="admin_list_users" style="width: 1000px; height: 300px;" title="Users List" >    	    	
	    <tr align="left">
		    <th field="id" width = "40"><h4>ID</h4></th>
		    <th field="created_at" width = "180"><h4>Date</h4></th>			    		    	
		    <th field="username" width = "100"><h4>Username</h4></th>
		    <th field="email" width = "200"><h4>Email</h4></th>
		</tr>
		<% @admin_users.each do |user| %>
	    <tr align="left">
		    <td width = "40"><h5><%= user.id %></h5></td>
		    <td width = "180"><h5><%= user.created_at %></h5></td>		    	
		    <td width = "100"><h5><%= user.username %></h5></td>
		    <td width = "200"><h5><%= user.email %></h5></td>
		    
		    <!-- = link_to('View', {:action => 'view', :id => user.id}) -->
		    		     			    
		</tr>
		<% end %>	    	
	</table>
	<%= will_paginate @admin_users %>

	<% else %>
	<div class="row" style="color: red;">
		<h3>No record for Users</h3>
	</div>
	<div class="row-end">&nbsp;</div>			
	<% end %>
	
					
<div class="row" style="height: 20px;"></div>
<div class="row-end">&nbsp;</div>				