config/routes.rb
Webknowadmin::Application.routes.draw do


  root to: 'admin_users#home'

  
  match '/signin', to: 'sessions#new', via: 'get'
  #match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signout', to: 'sessions#destroy', via: 'get'
  resources :sessions, only: [:new, :create, :destroy]



  resources :admin_users do
    collection do
      post :dbclear
    end
  end

  resources :admin_users do
    collection do
      post :dbdelete
    end
  end

  match '/admin_users_index', to: 'admin_users#index', via: 'get'  
  match '/admin_users_new', to: 'admin_users#new', via: 'get'  

  resources :admin_users



  get "static_pages/ajaxpostex"
  get "static_pages/serverside"
  get "static_pages/postjsonex"
  
  match '/JournalPosterPositions-1', to: 'journal1poster_positions#index', via: 'get'
  match '/JournalPosterCreate-1', to: 'journal1poster_positions#create', via: 'post'

  # match '/JournalPosterPositionsCoord', :to => 'journal1poster_positions#coord', :as => 'JournalPosterPositionsCoord', :via => [:post]
  # match '/publisher_journalposter_purchases/receipt', :to => 'publisher_journalposter_purchases#receipt', :as => 'publisher_journalposter_purchases_receipt', :via => [:get]
  
  # resources :journal1poster_positions do
    # collection do
      # post :demo_test_post
    # end
  # end

  # resources :journal1poster_positions do
    # collection do
      # post :coord
    # end
  # end
  
  resources :journal1poster_positions do
    collection do
      post :dbdelete
    end
  end
  
  # resources :journal1poster_positions do
    # member do
      # get 'coord'
    # end
  # end

  resources :journal1poster_positions





  match '/JournalPosterPositions-2', to: 'journal2poster_positions#index', via: 'get'
  resources :journal2poster_positions

  match '/JournalPosterPositions-3', to: 'journal3poster_positions#index', via: 'get'
  resources :journal3poster_positions

  match '/JournalPosterPositions-4', to: 'journal4poster_positions#index', via: 'get'
  resources :journal4poster_positions

  match '/JournalPosterPositions-5', to: 'journal5poster_positions#index', via: 'get'
  resources :journal5poster_positions




  match '/poster_map_1', to: 'journalposter__maps#index', via: 'get'
  resources :journalposter_maps








end

app/views/layouts/_footer_admin.html.erb
	<div style="height: 5px;"></div>


	<style>
		
		#kfooter {
			height: 100px;
			width: 100%;
			background-color: #000;
			
		}
		#kfooter .kfooter-title {
			color: #FFF;
			font-size: 11px;
			top: 13px;
			position: relative;
			font-family: KlavikaMedium;
			display: inline-block;
			float: left;
			margin-left: 40%;
		}
		#kfooter .kfooter-links {
			font-size: 11px;
			top: 17px;
			position: relative;
			font-family: KlavikaMedium;
			display: inline-block;
			float: right;
			margin-right: 5%;		
		}
		#kfooter .kfooter-links a {
			color: #fff;
		}		
		#kfooter .kfooter-logo {
			display: inline-block;
			float: left;
			margin-left: 5%;					
		}	
		#kfooter .kfooter-logo img {
			margin-top: 8px;
		}	
		#kfooter .kfooter-spacer {
			display: inline-block;
		}
		
	</style>

	<div id="kfooter">
		
		<div class="kfooter-logo">
			<img src="../repository/logo-icon-lc-transparent.png" height="25px">
		</div>
		
		<div class="kfooter-title">COPYRIGHT 2013 THE LEARNING COUNSEL</div>
		
		<!-- <div class="kfooter-links"><a href="/privacy">PRIVACY</a></div>		
		<div class="kfooter-spacer"></div>
		<div class="kfooter-links"><a href="/sponsor">SPONSOR</a></div>
		<div class="kfooter-spacer"></div>				
		<div class="kfooter-links"><a href="/contacts/new">CONTACT US</a></div>		 -->
		
				
	</div>
	

app/views/layouts/_nav_admin.html.erb
<style>

	@font-face {
	  	font-family: 'msyhb';
	  	src: url('/assets/msyhb.eot');	  
	  	src: url('/assets/msyhb.ttf') format('truetype');
	}
	@font-face {
		font-family: 'msyh';
	    src: url('/assets/msyh.eot');	  		
		src: url('/assets/msyh.ttf') format('truetype');
	}
	
	@font-face {
		font-family: digitgraphics;
		src: url('/assets/digitgraphics.eot');
	}

	@font-face {
		font-family: KlavikaExtraLight;
		src: url('/assets/KlavikaWebDisplayExtraLight.eot');
	}
		
	nav {
		font-family: msyh;
		position: relative;
		z-index: +10;
		height: 38px;
		box-shadow: 2px 2px 10px #000;
        background: -moz-linear-gradient(center bottom, #202631 10%, #3e464f 95%, #67717c 96%, #444f5e 99%); 
	}

 	/*
 	202631 -> 203121 -> 49704B -> 375239 -> 4F7551
	3e464f -> 3E4F4B -> 627A75 -> 50635F -> 496962 -> 49695A
	67717c -> 6F7C67 -> 95A38B -> 829179
	444f5e -> 4F5E44 -> 879E75 -> 67785A
	*/	

	nav a:hover {
	text-decoration: none;
	}
	nav ul {
		padding-left: 0px;
		margin-top: 0px;
		border-radius: 0px;  
		list-style: none;
		position: relative;
		display: inline-table;		
	}
	nav li {
		float: left;		
		display: inline;
	}
	nav ul:after {
		content: "";
		clear: both;
		display: block;
	}
	nav ul li:hover {
      background: -moz-linear-gradient(center bottom, #202631 10%, #3e464f 95%, #67717c 96%, #444f5e 99%); 
		
		/*background: #56854E; 
		background: linear-gradient(top, #56854E 0%, #254520 100%);  
		background: -moz-linear-gradient(top, #56854E 0%, #254520 100%); 
		background: -webkit-linear-gradient(top, #56854E 0%,#254520 100%);*/		
	}
	nav ul li:hover a {
		color: #BFFAB9;
	}
	nav ul li a {
		display: block;
		padding: 9px 9px;
		color: #fff;
		text-decoration: none;
		font-size: 20px;
	}
	nav ul ul {
		display: none;
	}
	/*nav ul li:active a {		
		background: #56854E; 
		background: linear-gradient(top, #56854E 0%, #254520 100%);  
		background: -moz-linear-gradient(top, #56854E 0%, #254520 100%); 
		background: -webkit-linear-gradient(top, #56854E 0%,#254520 100%);		
      	background: -moz-linear-gradient(center bottom, #4F7551 10%, #49695A 95%, #829179 96%, #67785A 99%);      
        background: -moz-linear-gradient(center bottom, #202631 10%, #3e464f 95%, #67717c 96%, #444f5e 99%);		
		color:#F0F56E;
		outline: none;
	}*/	
	nav ul ul {
		background-color:rgba(0, 0, 0, 0.6);
		-moz-box-shadow:2px 2px 20px rgba(0,0,0,.8);
		-webkit-box-shadow:2px 20px 2px rgba(0,0,0,.8);
		box-shadow:2px 2px 20px rgba(0,0,0,.8);
		border-bottom-left-radius: 10px;
   		border-bottom-right-radius: 10px;
		position: absolute;
	}
	nav a:active {
		background-color:rgba(0, 0, 0, 0.6);
		-moz-box-shadow:2px 2px 20px rgba(0,0,0,.8);
		-webkit-box-shadow:2px 20px 2px rgba(0,0,0,.8);
		box-shadow:2px 2px 20px rgba(0,0,0,.8);
		color:#F0F56E;
		outline: none;
	}
	nav ul ul li:first-child {
		float: none; 
		position: relative;
	}
	nav ul ul li {
		float: none; 
		position: relative;
	}
	nav ul ul li a {
		padding: 10px 20px;
		border-bottom-left-radius: 0px;
   		border-bottom-right-radius: 0px;
	}
	nav ul ul li:last-child a {
		padding: 10px 20px;
		border-bottom-left-radius: 10px;
   		border-bottom-right-radius: 10px;
	}
	nav ul ul li a:hover {
		background-color:rgba(0, 0, 0, 0.4);
		color: #2AF707;
	}
	/*nav ul ul li a:active {
		background-color:rgba(0, 0, 0, 0.4);
		color:#F0F56E;
		outline: none;
	}*/
	nav ul ul ul {
		position: absolute;
		left: 100%; top:0;
	}
	nav p {
		padding: 14px 30px 0px 0px; 
		color: orange;
		font-size: 16px;
		float: right;
	}
	
	/*.extendfull, .extendleft
	{
		margin-left: -3000px;
		padding-left: 3000px;
	}
	.extendfull, .extendright
	{
		margin-right: -3000px;
		padding-right: 3000px;
	}	*/
     
</style>

	 <nav style="position: fixed; width: 100%;">	 	
		<div id="topNav">
			
			<ul style="width: 100%; padding-left: 8%;">
				<!-- <li><a href="/index">Home</a></li>
				<li><a href="/edmatchups">EdMatchUp</a>
					<ul>
						<li><a href="/edmatchups">
								<img src="/assets/image_ed_flow_chart_small.png" style="width: auto;">
							</a>
						</li>
					</ul>					
				</li> -->
				<li><a href="/admin_users/index">Database</a>
					<ul>
						<!-- <li><= link_to 'Contacts', admin_contacts_index_path ></li> -->
						<li><%= link_to 'Users', admin_users_index_path %></li>
						
						<!-- <li><a href="admin_users/list">Users</a></li>
						<li><a href="admin_users/contacts">Contacts</a></li>
						<li><a href="admin_users/institues">Institutes</a></li>
						<li><a href="admin_users/publishers">Publishers</a></li> -->						
					</ul>					
				</li>
								
				<li><a href="#">Journal Posters</a>
					<ul>
						<li>
							<%= link_to 'Journal Posters', '/JournalPosterPositions-1' %>
						</li>
					</ul>
				</li>
				
				
				<% if !session[:username] %>
					<li style="float: right; padding-right: 40px;"><a href="/signin">Sign In</a></li>
					<!-- <li style="float: right; padding-right: 0px;"><a href="/signup">Join</a></li> -->					
				<% else %>
					
					<% if session[:has_account] %>		
					<li style="float: right;"><a href="/home">Profile</a></li>
					<% end %>

					<li style="float: right; padding-right: 10%;"><a href="/signout">Sign Out</a></li>
					<p><%= session[:username] %></p>
					<li style="float: right;">
						<!-- <#%= link_to 'Profile', admin_user_profiles_index_path %#> -->
					</li>

				<% end %>
				
			</ul>
			
		</div>
	</nav>

    <script>
      
        (function($){  
            var nav = $("#topNav");  
            nav.find("li").each(function() {  
                if ($(this).find("ul").length > 0) {  
                    $(this).mouseenter(function() {  
                        $(this).find("ul").stop(true, true).slideDown(300);  
                    });  
                    $(this).mouseleave(function() {  
                        $(this).find("ul").stop(true, true).slideUp(300);  
                    });  
                }  
            });  
        })(jQuery);
          
    </script>  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signin.html.erb
<style>
	
	#signin-page {
		background-color: #C7C7C7;
	}
	
	
	#signin-page #signin-page-inner {
	    width: 50%;
	    margin: 0 auto;
		height: 100px; 
		text-align: center; 

		vertical-align: center; 
		background-color: #A60000; 
		position: relative; 
	}	
	
</style>

<div id="signin-page">

	<div style="height: 200px;"></div>
		
	<a href="sessions/new">		
	<div id="signin-page-inner">
		
     <!-- link_to "Sign In", 'sessions/new'  -->
     		
	</div>
	</a>
	
	<div style="height: 750px;"></div>
	
</div>

app/views/layouts/admin_users.html.erb
<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">
								    	
  		<title><%= full_title(yield(:title)) %></title> 

    	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  		
		<!-- <link rel="icon" type="image/png" href="/assets/logo-lc-round-fav.png" /> -->
				  		
   		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>    		   		
    	
  		<%= include_gon %>
    	
	  	<%= csrf_meta_tags %>
	  	<%= render 'layouts/shim' %>  
		                		
    </head>
	<body>
		
		
		<% if !signed_in? %> 
		
			<%= render 'layouts/signin' %> 
		
		<% else %>

			<%= render 'layouts/nav_admin' %>
			
		<div style="width: 1200px; margin-right: auto; margin-left: auto; background: #fff;">						
			
			<%= yield %> 

		</div>
		
		<%= render 'layouts/footer_admin' %>

		<% end %>

		<%= debug(params) if Rails.env.development? %>
		
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webknowadmin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/journalposter.html.erb
<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">
								    	
  		<title><%= full_title(yield(:title)) %></title> 

    	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  		
		<link rel="icon" type="image/png" href="/assets/knowstory-icon-fav.png" />		
  					  		
   		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>    		   		
    	
	  	<%= csrf_meta_tags %>
	  	<%= render 'layouts/shim' %>  

  		<%= include_gon %>
		                		
    </head>
    
	<body>
		
		<%= render 'layouts/nav_admin' %>
								
		<%= yield %> 

		<%= render 'layouts/footer_admin' %>
		
		<%= debug(params) if Rails.env.development? %>
		
	</body>
	
</html>

app/views/layouts/journalposter_map.html.erb
<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">
								    	
  		<title></title> 

    	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  		
		<link rel="icon" type="image/png" href="/assets/knowstory-icon-fav.png" />		
  					  		
   		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>    		   		
    	
	  	<%= csrf_meta_tags %>
	  	<%= render 'layouts/shim' %>  

  		<%= include_gon %>
		                		
    </head>
    
	<body>
		<%= yield %> 
	</body>
	
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">

  		<title><%= full_title(yield(:title)) %></title> 
  		
    	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  		
  		
		<!-- <link rel="icon" type="image/png" href="/assets/logo-lc-round-fav.png" /> -->
  		
  		
   		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>    		   		
    	
	  	<%= csrf_meta_tags %>
	  	<%= render 'layouts/shim' %>  
  		
	<style>
	
		#signin-body {
			background-color: #C7C7C7;
		}
	
	</style>

    </head>
    <body id="signin-body">
		
		 <!-- if !session[:admin] 	
			 render 'layouts/header' 
		 else 
			 render 'layouts/header_admin' 			
		 end  -->
		 		
		<!-- <div style="width: 1000px; margin-right: auto; margin-left: auto;">			 -->
						
			<%= yield %> 
	
			 <!-- render 'layouts/footer'  -->
			 			
			<%= debug(params) if Rails.env.development? %>
		
		<!-- </div> -->		
		
    </body>
</html>